"""auto-vote

Revision ID: 7e0732c2f4fe
Revises: 1bfd79dae795
Create Date: 2025-03-07 23:41:28.352468

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e0732c2f4fe'
down_revision: Union[str, None] = '1bfd79dae795'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table('votes',
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('post_id', sa.Integer(), nullable=False),        
        sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint('user_id', 'post_id')
    )
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
